### ISSUE TITLE
Segment Fault

### ISSUE THREAD

**Issue by Heitortadeu** [azerothcore/mod-detailed-logging#9]
In order to let them know that a mod is causing thread failure on the server.

![image](https://user-images.githubusercontent.com/58153179/139565787-0ea7faf7-ff25-4344-a31b-6c70d76b5382.png)

![image](https://user-images.githubusercontent.com/58153179/139565794-8c39b9e0-c4aa-4e3b-b118-602928f841cf.png)

**Comment by Winfidonarleyan** [comment]
Next time use text

**Comment by Heitortadeu** [comment]
sorry, next time i send good morning.

**Comment by Heitortadeu** [comment]
> Next time use text for create issues

sorry, next time i send good morning.
